### ISSUE TITLE
Search result not visible

### ISSUE THREAD

**Issue by rkversion** [kartta-labs/kartta#33]
Search for "Albert Neuhuysstraat" in Amsterdam: after clicking on the relevant result link the 
landing page includes the searched-for street, but the view is zoomed out too much so that 
the street name is not visible, and it is impossible to find it, unless one knows the area well.

Landing page for the result should be at zoom level sufficient to easily see what was searched for.

**Comment by embeepea** [comment]
I think this is resolved now; see https://github.com/kartta-labs/kartta/pull/37.

The initial implementation of the search box had the results zoom level hardcoded at 13.5.  The PR above chooses a zoom level based on the bounding box of the search results returned from nominatim.
